### ISSUE TITLE
LDAP Escape prevents userPrincipalName from being used as username

### ISSUE THREAD

**Issue by lrsksr** [famedly/uia-proxy#173]
In AD the userPrincipalName is `username@domain`. In https://github.com/famedly/uia-proxy/blob/main/src/passwordproviders/passwordprovider_ldap.ts#L436 we filter out `@` so the UPN can not be used as a login name.

According to https://cheatsheetseries.owasp.org/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.html the `@` doesn't need to be escaped, but proper research should still be done before just adding it to the allowed characters.

**Comment by nikzen** [comment]
I will have a look, thanks for sharing the findings.
