### ISSUE TITLE
Implement curamenta fixes on 0.8 branch

### ISSUE THREAD

**Issue by emgrav** [famedly/uia-proxy#175]
We need to include the backported changes in the `0.7.14-curamenta` tag (from March 10 and forward) into the current latest version, `v0.8.5`.

**Comment by nikzen** [comment]
Difference can be find here: https://gitlab.com/famedly/company/backend/services/uia-proxy/-/compare/v0.8.4...v0.7.14-curamenta?from_project_id=16123300&straight=false

**Comment by pi-314** [comment]
On this occasion we should also check, if we can upgrade some dependencies to get rid of audit findings. For v8.0.5 currently we have 8 vulnerabilities (3 moderate, 3 high, 2 critical), all coming from transitive npm package dependencies. Few are marked as 'breaking change', but the code seems not to rely on any deprecated features, so it should be possible just to switch to the newer versions.

**Comment by pi-314** [comment]
bump: We still need a debug session with curamenta to check, which functionality is missing in -rc0.
